version: "3.8"

services:
  app:
    image: my-secure-app
    container_name: secure-app
    secrets:
      - api_key
    environment:
      - API_KEY_FILE=/run/secrets/api_key

secrets:
  api_key:
    file: ./api_key.txt

